### ISSUE TITLE
Workflow fails with `Could not find 'java' executable in JAVA_HOME or PATH.`

### ISSUE THREAD

**Issue by thmspl** [kitabisa/sonarqube-action#17]
### Issue and Steps to Reproduce

Everytime I'm trying to push my code to the sonarcloud with your workflow I get the following error:

> Could not find 'java' executable in JAVA_HOME or PATH.

Just create a workflow file like stated under "Workflow file" and run the workflow. I get this error on multiple repositories.

### Workflow file

That's my workflow yml file which I'm using:

````
name: Maven CI

on: [push]

jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@master
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          projectKey: "diary"
````

### Specifications

  - Version: v1.1.0 (latest)
  - Platform: ubuntu-latest
  - Java Version: JDK 11
