### ISSUE TITLE
AnalysisException: Your project contains .java files

### ISSUE THREAD

**Issue by sheu** [kitabisa/sonarqube-action#36]
### Issue and Steps to Reproduce

I added this action to one of my projects and I got this error.  What is confusing is that it works without issues one of my projects.

```
- name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          host: ${{ env.SONAR_URL }}
          login: ${{ secrets.SONARQUBE_AUTH_TOKEN }}
          projectKey: ${{ env.PROJECT_KEY }}
```

### Versions
1.2.0

#### Expected
A way to set other properties or successful scan

#### Actual
Exception thrown
```
RROR: Error during SonarScanner execution
org.sonar.java.AnalysisException: Your project contains .java files, please provide compiled classes with sonar.java.binaries property, or exclude them from the analysis with sonar.exclusions property.
```

### Specifications

  - Version: 
  - Platform:
  - Subsystem:
